let x= 10;
console.log(x);
console.log(x+=5);
console.log(x);
console.log(x-=10);
console.log(x);
console.log(x*=2);
console.log(x);
console.log(x**=2);
console.log(x);
console.log(x/=3);
console.log(x%=x);
console.log(x);
